name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build-push
        uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          username: pmjohann
          password: ${{ secrets.PAT }}
          tags: pmjohann/mdbook:latest
